export default {
  about: "درباره",
  appTitle: "آزمایشات موبایل آرنا",
  cancel: "لغو",
  clear: "پاک کردن",
  close: "بستن",
  confirm: "تایید",
  confirmClearSelectedValue: "آیا از پاک کردن مقدار انتخاب شده مطمئن هستید؟",
  confirmClearSelectedValue_plural:
    "آیا از پاک کردن مقادیر انتخاب شده مطمئن هستید؟",
  createdOn: "ایجاد شده در",
  delete: "حذف",
  deleteSelectedTitle: "حذف انتخاب",
  details: "جزئیات",
  done: "انجام شد",
  empty: "--- خالی کردن ---",
  error: "خطا",
  exit: "خروج",
  export: "اکسپورت",
  false: "خیر",
  filter: "فیلتر",
  fromToOf: `{{from}} به {{to}} از {{of}}`,
  goBack: "بازگشت",
  info: "اطلاعات",
  label: "برچسب",
  modifiedOn: "تغییر یافته در",
  name: "نام",
  networkNotAvailable: "شبکه در دسترس نیست!",
  newItemWithParam: "جدید {{item}}",
  no: "خیر",
  noItemsMatchingSearch: "موردی مطابق با جستجوی شما یافت نشد",
  notEnoughDiskSpace:
    "فضای خالی دیسک کافی نیست (به {{requiredSpace}} فضای بیشتر نیاز است)",
  ok: "باشه",
  path: "مسیر",
  rowsPerPage: "ردیف در هر صفحه",
  search: "جستجو",
  selectAnItem: "یک مورد را انتخاب کنید",
  selectNewItems: "موارد جدید را انتخاب کنید",
  size: "اندازه",
  sizeAvailable: "{{size}} در دسترس",
  somethingWentWrong: "مشکلی رخ داده است: {{error}}",
  srs: "SRS",
  status: "وضعیت",
  stop: "توقف",
  swipeToConfirm: "برای تأیید بکشید",
  textCopiedToClipboard: "متن به کلیپ بورد کپی شد",
  true: "بله",
  yes: "بله",

  timePart: {
    year: "سال",
    year_plural: "سال",
    month: "ماه",
    month_plural: "ماه",
    day: "روز",
    day_plural: "روز",
    hour: "ساعت",
    hours: "ساعت",
    minute: "دقیقه",
    minute_plural: "دقیقه",
    second: "ثانیه",
    second_plural: "ثانیه",
  },
  remainingTime: {
    canLastHoursAndMinutes:
      "ممکن است حدود {{hours}} ساعت و {{minutes}} دقیقه طول بکشد",
    canLastTimePart: "ممکن است حدود {{count}} {{timePart}} طول بکشد",
    hoursAndMinutesShort: "{{hours}} ساعت و {{minutes}} دقیقه",
    lessThanOneTimePart: "کمتر از یک {{timePart}} باقی مانده",
    timePartLeft: "{{count}} {{timePart}} باقی مانده",
  },
};
