export default {
  appTitle: "Arena Mobile Experiments",
  cancel: "Cancel",
  close: "Close",
  confirm: "Confirm",
  done: "Done",
  empty: "--- EMPTY ---",
  export: "Export",
  false: "False",
  info: "Info",
  label: "Label",
  modifiedOn: "Modified on",
  name: "Name",
  networkNotAvailable: "Network not available!",
  no: "No",
  search: "Search",
  selectAnItem: "Select an item",
  srs: "SRS",
  textCopiedToClipboard: "Text copied to clipboard",
  true: "True",
  yes: "Yes",
};
