export default {
  appTitle: "My Arena Mobile",
  cancel: "Cancel",
  confirm: "Confirm",
  empty: "--- EMPTY ---",
  false: "False",
  label: "Label",
  modifiedOn: "Modified on",
  name: "Name",
  networkNotAvailable: "Network not available!",
  no: "No",
  search: "Search",
  selectAnItem: "Select an item",
  true: "True",
  yes: "Yes",
};
