export default {
  about: "ስለ",
  appTitle: "የአሬና ሞባይል ሙከራዎች",
  cancel: "ይቅር",
  clear: "አጽዳ",
  close: "ዝጋ",
  confirm: "አረጋግጥ",
  confirmClearSelectedValue: "የተመረጠውን እሴት አጽዳ?",
  confirmClearSelectedValue_plural: "የተመረጡትን እሴቶች አጽዳ?",
  createdOn: "የተፈጠረው በ",
  delete: "ሰርዝ",
  deleteSelectedTitle: "የተመረጡትን ሰርዝ",
  details: "ዝርዝሮች",
  done: "ተከናውኗል",
  empty: "--- ባዶ ---",
  error: "ስህተት",
  exit: "ውጣ",
  export: "ላክ",
  false: "ሐሰት",
  filter: "አጣራ",
  fromToOf: "{{from}}-{{to}} ከ {{of}}",
  goBack: "ተመለስ",
  info: "መረጃ",
  label: "መለያ",
  modifiedOn: "የተሻሻለው በ",
  name: "ስም",
  networkNotAvailable: "አውታረ መረብ የለም!",
  newItemWithParam: "አዲስ {{item}}",
  no: "አይ",
  noItemsMatchingSearch: "ከፍለጋዎ ጋር የሚዛመድ ንጥል የለም",
  notEnoughDiskSpace: "በቂ ነፃ የዲስክ ቦታ የለም (ተጨማሪ {{requiredSpace}} ያስፈልጋል)",
  ok: "እሺ",
  path: "መንገድ",
  rowsPerPage: "በገጽ ያሉ ረድፎች",
  search: "ፈልግ",
  selectAnItem: "አንድ ንጥል ይምረጡ",
  selectNewItems: "አዲስ ንጥሎችን ይምረጡ",
  size: "መጠን",
  sizeAvailable: "{{size}} ይገኛል",
  somethingWentWrong: "አንድ ችግር ተከስቷል: {{error}}",
  srs: "SRS",
  status: "ሁኔታ",
  stop: "አቁም",
  swipeToConfirm: "ለማረጋገጥ ያንሸራትቱ",
  textCopiedToClipboard: "ጽሑፉ ወደ ቅንጥብ ሰሌዳ ተቀድቷል",
  true: "እውነት",
  yes: "አዎ",
  timePart: {
    year: "ዓመት",
    year_plural: "ዓመታት",
    month: "ወር",
    month_plural: "ወራት",
    day: "ቀን",
    day_plural: "ቀናት",
    hour: "ሰዓት",
    hours: "ሰዓታት",
    minute: "ደቂቃ",
    minute_plural: "ደቂቃዎች",
    second: "ሰከንድ",
    second_plural: "ሰከንዶች",
  },
  remainingTime: {
    canLastHoursAndMinutes:
      "ለ {{hours}} ሰዓታት እና {{minutes}} ደቂቃዎች ያህል ሊቆይ ይችላል",
    canLastTimePart: "ለ {{count}} {{timePart}} ያህል ሊቆይ ይችላል",
    hoursAndMinutesShort: "{{hours}} ሰዓታት እና {{minutes}} ደቂቃዎች",
    lessThanOneTimePart: "ከአንድ {{timePart}} በታች ቀርቷል",
    timePartLeft: "{{count}} {{timePart}} ቀርቷል",
  },
};
