export default {
  backup: "Sicherung",
  changelog: "Änderungsprotokoll",
  confirmExit: {
    title: "Beenden",
    message: "App beenden?\nAlle Änderungen wurden bereits gespeichert.",
  },
  currentVersion: "Aktuelle Version",
  fullBackup: {
    confirmMessage:
      "Vollständige Sicherung erstellen?\nDie Größe beträgt ca. {{size}}.",
    confirmTitle: "Sicherung erstellen",
    error: "Fehler beim Erstellen der vollständigen Sicherung: {{details}}",
    shareTitle: "AME-Vollsicherung teilen",
    title: "Vollsicherung",
  },
  initializationStep: {
    starting: "Starten",
    fetchingDeviceInfo: "Geräteinformationen abrufen",
    fetchingSettings: "Einstellungen abrufen",
    storingSettings: "Einstellungen speichern",
    settingFullScreen: "Vollbild einstellen",
    settingKeepScreenAwake: "Bildschirm aktiv lassen einstellen",
    startingGpsLocking: "GPS-Fixierung starten",
    initializingDb: "DB initialisieren",
    startingDbMigrations: "DB-Migrationen starten",
    fetchingSurveys: "Umfragen abrufen",
    importingDemoSurvey: "Demo-Umfrage importieren",
    fetchingAndSettingLocalSurveys: "Lokale Umfragen abrufen und einstellen",
    fetchingAndSettingSurvey: "Umfrage abrufen und einstellen",
    checkingLoggedIn: "Angemeldet prüfen",
    complete: "Abgeschlossen",
  },
  pleaseWaitMessage: "Bitte warten...",
  update: "Aktualisieren",
  updateAvailable: "Update verfügbar",
};
