nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmScopes:
  "openforis":
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}
    npmRegistryServer: "https://npm.pkg.github.com"
