export default {
  about: "Acerca de",
  cancel: "Cancelar",
  clear: "Limpiar",
  close: "Cerrar",
  confirm: "Confirmar",
  confirmClearSelectedValue: "¿Limpiar el valor seleccionado?",
  confirmClearSelectedValue_plural: "¿Limpiar los valores seleccionados?",
  createdOn: "Creado el",
  delete: "Eliminar",
  deleteSelectedTitle: "Eliminar seleccionados",
  details: "Detalles",
  done: "Hecho",
  empty: "--- VACÍO ---",
  error: "Error",
  exit: "Salir",
  export: "Exportar",
  false: "Falso",
  filter: "Filtrar",
  fromToOf: "{{from}}-{{to}} de {{of}}",
  goBack: "Volver",
  info: "Información",
  label: "Etiqueta",
  modifiedOn: "Modificado el",
  name: "Nombre",
  networkNotAvailable: "¡Red no disponible!",
  newItemWithParam: "Nuevo {{item}}",
  no: "No",
  noItemsMatchingSearch: "No hay ningún elemento que coincida con su búsqueda",
  notEnoughDiskSpace:
    "No hay suficiente espacio libre en disco (se necesitan {{requiredSpace}} más)",
  ok: "Aceptar",
  path: "Ruta",
  rowsPerPage: "Filas por página",
  search: "Buscar",
  selectAnItem: "Seleccionar un elemento",
  selectNewItems: "Seleccionar nuevos elementos",
  size: "Tamaño",
  sizeAvailable: "{{size}} disponibles",
  somethingWentWrong: "Algo salió mal: {{error}}",
  srs: "SRS",
  status: "Estado",
  stop: "Detener",
  swipeToConfirm: "Deslizar para confirmar",
  textCopiedToClipboard: "Texto copiado al portapapeles",
  true: "Verdadero",
  yes: "Sí",
  timePart: {
    year: "año",
    year_plural: "años",
    month: "mes",
    month_plural: "meses",
    day: "día",
    day_plural: "días",
    hour: "hora",
    hours: "horas",
    minute: "minuto",
    minute_plural: "minutos",
    second: "segundo",
    second_plural: "segundos",
  },
  remainingTime: {
    canLastHoursAndMinutes:
      "Puede durar alrededor de {{hours}} h y {{minutes}} min",
    canLastTimePart: "Puede durar alrededor de {{count}} {{timePart}}",
    hoursAndMinutesShort: "{{hours}} h y {{minutes}} min",
    lessThanOneTimePart: "queda menos de un {{timePart}}",
    timePartLeft: "quedan {{count}} {{timePart}}",
  },
};
