export default {
  about: "О программе",
  appTitle: "Мобильные эксперименты Arena",
  cancel: "Отмена",
  clear: "Очистить",
  close: "Закрыть",
  confirm: "Подтвердить",
  confirmClearSelectedValue: "Очистить выбранное значение?",
  confirmClearSelectedValue_plural: "Очистить выбранные значения?",
  createdOn: "Создано",
  delete: "Удалить",
  deleteSelectedTitle: "Удалить выбранное",
  details: "Подробности",
  done: "Готово",
  empty: "--- ПУСТО ---",
  error: "Ошибка",
  exit: "Выход",
  export: "Экспорт",
  false: "Ложное значение",
  filter: "Фильтр",
  fromToOf: "{{from}}-{{to}} из {{of}}",
  goBack: "Назад",
  info: "Информация",
  label: "Метка",
  modifiedOn: "Изменено",
  name: "Имя",
  networkNotAvailable: "Сеть недоступна!",
  newItemWithParam: "Новый {{item}}",
  no: "Нет",
  noItemsMatchingSearch: "По Вашему запросу нет элементов",
  notEnoughDiskSpace:
    "Недостаточно свободного места на диске (требуется еще {{requiredSpace}})",
  ok: "Ок",
  path: "Путь доступа",
  rowsPerPage: "Строк на странице",
  search: "Поиск",
  selectAnItem: "Выберите элемент",
  selectNewItems: "Выберите новые элементы",
  size: "Размер",
  sizeAvailable: "{{size}} доступно",
  somethingWentWrong: "Что-то пошло не так: {{error}}",
  srs: "SRS",
  status: "Статус",
  stop: "Стоп",
  swipeToConfirm: "Смахните для подтверждения",
  textCopiedToClipboard: "Текст скопирован в буфер обмена",
  true: "Правильное значение",
  yes: "Да",
  timePart: {
    year: "год",
    year_plural: "лет",
    month: "мес.",
    month_plural: "мес.",
    day: "д.",
    day_plural: "д.",
    hour: "ч.",
    hours: "ч.",
    minute: "мин.",
    minute_plural: "мин.",
    second: "сек.",
    second_plural: "сек.",
  },
  remainingTime: {
    canLastHoursAndMinutes: "Может длиться около {{hours}} ч и {{minutes}} мин",
    canLastTimePart: "Может длиться около {{count}} {{timePart}}",
    hoursAndMinutesShort: "{{hours}} ч и {{minutes}} мин",
    lessThanOneTimePart: "осталось меньше одного {{timePart}}",
    timePartLeft: "осталось {{count}} {{timePart}}",
  },
};
