export default {
  clearCredentials: "Очистить учетные данные",
  clearCredentialsConfirmMessage: "Очистить учетные данные пользователя?",
  email: "Электронная почта",
  errorConnectingWithServer: "Ошибка подключения к серверу",
  forgotPassword: "Забыли пароль?",
  login: "Войти",
  logout: "Выйти",
  logoutConfirmMessage: "Выйти и очистить учетные данные пользователя?",
  password: "Пароль",
  requestAccess: "Вы впервые в Arena? Запросить доступ",
  serverUrl: "URL сервера",
  serverUrlNotValid: "Неверный URL сервера",
  serverUrlType: {
    default: "По умолчанию",
    custom: "Пользовательский",
  },
  testUrl: "Проверить URL",
  title: "Подключение к удаленному серверу",
};
