export default {
  about: "Sobre",
  cancel: "Cancelar",
  clear: "Limpar",
  close: "Fechar",
  confirm: "Confirmar",
  confirmClearSelectedValue: "Limpar o valor selecionado?",
  confirmClearSelectedValue_plural: "Limpar os valores selecionados?",
  createdOn: "Criado em",
  delete: "Excluir",
  deleteSelectedTitle: "Excluir selecionados",
  details: "Detalhes",
  done: "Concluído",
  empty: "--- VAZIO ---",
  error: "Erro",
  exit: "Sair",
  export: "Exportar",
  false: "Falso",
  filter: "Filtrar",
  fromToOf: "{{from}}-{{to}} de {{of}}",
  goBack: "Volte",
  info: "Informação",
  label: "Etiqueta",
  modifiedOn: "Modificado em",
  name: "Nome",
  networkNotAvailable: "Rede não disponível!",
  newItemWithParam: "Novo {{item}}",
  no: "Não",
  noItemsMatchingSearch: "Não há nenhum item correspondente à sua pesquisa",
  notEnoughDiskSpace:
    "Espaço em disco insuficiente (são necessários mais {{requiredSpace}})",
  ok: "Ok",
  path: "Caminho",
  rowsPerPage: "Linhas por página",
  search: "Pesquisar",
  selectAnItem: "Selecionar um item",
  selectNewItems: "Selecionar novos itens",
  size: "Tamanho",
  sizeAvailable: "{{size}} disponíveis",
  somethingWentWrong: "Algo deu errado: {{error}}",
  srs: "SRS",
  status: "Estado",
  stop: "Parar",
  swipeToConfirm: "Deslize para confirmar",
  textCopiedToClipboard: "Texto copiado para a área de transferência",
  true: "Verdadeiro",
  yes: "Sim",
  timePart: {
    year: "ano",
    year_plural: "anos",
    month: "mês",
    month_plural: "meses",
    day: "dia",
    day_plural: "dias",
    hour: "hora",
    hours: "horas",
    minute: "minuto",
    minute_plural: "minutos",
    second: "segundo",
    second_plural: "segundos",
  },
  remainingTime: {
    canLastHoursAndMinutes: "Pode durar cerca de {{hours}} h e {{minutes}} min",
    canLastTimePart: "Pode durar cerca de {{count}} {{timePart}}",
    hoursAndMinutesShort: "{{hours}} h e {{minutes}} min",
    lessThanOneTimePart: "menos de um {{timePart}} restante",
    timePartLeft: "{{count}} {{timePart}} restantes",
  },
};
