const RECORD_SET = "RECORD_SET";
const PAGE_SELECTOR_MENU_OPEN_SET = "PAGE_SELECTOR_MENU_OPEN_SET";
const PAGE_ENTITY_SET = "PAGE_ENTITY_SET";
const PAGE_ENTITY_ACTIVE_CHILD_INDEX_SET = "PAGE_ENTITY_ACTIVE_CHILD_INDEX_SET";
const DATA_ENTRY_RESET = "DATA_ENTRY_RESET";

export const DataEntryActionTypes = {
  RECORD_SET,
  PAGE_SELECTOR_MENU_OPEN_SET,
  PAGE_ENTITY_SET,
  PAGE_ENTITY_ACTIVE_CHILD_INDEX_SET,
  DATA_ENTRY_RESET,
};
