export default {
  about: "À propos",
  cancel: "Annuler",
  clear: "Effacer",
  close: "Fermer",
  confirm: "Confirmer",
  confirmClearSelectedValue: "Effacer la valeur sélectionnée ?",
  confirmClearSelectedValue_plural: "Effacer les valeurs sélectionnées ?",
  createdOn: "Créé le",
  delete: "Supprimer",
  deleteSelectedTitle: "Supprimer la sélection",
  details: "Détails",
  done: "Terminé",
  empty: "--- VIDE ---",
  error: "Erreur",
  exit: "Quitter",
  export: "Exporter",
  false: "Faux",
  filter: "Filtrer",
  fromToOf: "{{from}}-{{to}} sur {{of}}",
  info: "Info",
  label: "Étiquette",
  modifiedOn: "Modifié le",
  name: "Nom",
  networkNotAvailable: "Réseau non disponible !",
  newItemWithParam: "Nouveau {{item}}",
  no: "Non",
  noItemsMatchingSearch: "Aucun élément ne correspond à votre recherche",
  notEnoughDiskSpace:
    "Espace disque insuffisant ({{requiredSpace}} supplémentaires sont nécessaires)",
  ok: "Ok",
  path: "Chemin",
  rowsPerPage: "Lignes par page",
  search: "Rechercher",
  selectAnItem: "Sélectionner un élément",
  selectNewItems: "Sélectionner de nouveaux éléments",
  size: "Taille",
  sizeAvailable: "{{size}} disponibles",
  somethingWentWrong: "Une erreur s'est produite : {{error}}",
  srs: "SRS",
  status: "Statut",
  stop: "Arrêter",
  swipeToConfirm: "Glisser pour confirmer",
  textCopiedToClipboard: "Texte copié dans le presse-papiers",
  true: "Vrai",
  yes: "Oui",
  timePart: {
    year: "an",
    year_plural: "ans",
    month: "mois",
    month_plural: "mois",
    day: "jour",
    day_plural: "jours",
    hour: "heure",
    hours: "heures",
    minute: "minute",
    minute_plural: "minutes",
    second: "seconde",
    second_plural: "secondes",
  },
  remainingTime: {
    canLastHoursAndMinutes:
      "Cela peut durer environ {{hours}} h et {{minutes}} min",
    canLastTimePart: "Cela peut durer environ {{count}} {{timePart}}",
    hoursAndMinutesShort: "{{hours}} h et {{minutes}} min",
    lessThanOneTimePart: "moins d'un {{timePart}} restant",
    timePartLeft: "{{count}} {{timePart}} restants",
  },
};
