export const SurveyActionTypes = {
  CURRENT_SURVEY_SET: "CURRENT_SURVEY_SET",
  CURRENT_SURVEY_PREFERRED_LANG_SET: "CURRENT_SURVEY_PREFERRED_LANG_SET",
  CURRENT_SURVEY_CYCLE_SET: "CURRENT_SURVEY_CYCLE_SET",
  SURVEYS_LOCAL_SET: "SURVEYS_LOCAL_SET",
};
